// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: thumbnail/thumbnail.proto

package thumbnail

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ThumbailClient is the client API for Thumbail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThumbailClient interface {
	GetThumbnail(ctx context.Context, in *Url, opts ...grpc.CallOption) (*Img, error)
}

type thumbailClient struct {
	cc grpc.ClientConnInterface
}

func NewThumbailClient(cc grpc.ClientConnInterface) ThumbailClient {
	return &thumbailClient{cc}
}

func (c *thumbailClient) GetThumbnail(ctx context.Context, in *Url, opts ...grpc.CallOption) (*Img, error) {
	out := new(Img)
	err := c.cc.Invoke(ctx, "/thumbnail.Thumbail/GetThumbnail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThumbailServer is the server API for Thumbail service.
// All implementations must embed UnimplementedThumbailServer
// for forward compatibility
type ThumbailServer interface {
	GetThumbnail(context.Context, *Url) (*Img, error)
	mustEmbedUnimplementedThumbailServer()
}

// UnimplementedThumbailServer must be embedded to have forward compatible implementations.
type UnimplementedThumbailServer struct {
}

func (UnimplementedThumbailServer) GetThumbnail(context.Context, *Url) (*Img, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnail not implemented")
}
func (UnimplementedThumbailServer) mustEmbedUnimplementedThumbailServer() {}

// UnsafeThumbailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThumbailServer will
// result in compilation errors.
type UnsafeThumbailServer interface {
	mustEmbedUnimplementedThumbailServer()
}

func RegisterThumbailServer(s grpc.ServiceRegistrar, srv ThumbailServer) {
	s.RegisterService(&Thumbail_ServiceDesc, srv)
}

func _Thumbail_GetThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Url)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbailServer).GetThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thumbnail.Thumbail/GetThumbnail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbailServer).GetThumbnail(ctx, req.(*Url))
	}
	return interceptor(ctx, in, info, handler)
}

// Thumbail_ServiceDesc is the grpc.ServiceDesc for Thumbail service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Thumbail_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thumbnail.Thumbail",
	HandlerType: (*ThumbailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThumbnail",
			Handler:    _Thumbail_GetThumbnail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thumbnail/thumbnail.proto",
}
